[features]
seeds = false
[programs.devnet]
whitelist_pda = "5RwKyqR6cDzFiqB5qfBsyqxzb6QuaRy249NwxJJ2154v"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ademola/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
