[features]
seeds = false
[programs.devnet]
whitelist_pda = "HqBtRNgYEFDDCiDh2jvt33MA9ZkC1hs59eQ5GLR3TfEu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ademola/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
